---
title: "BISC_2018"
author: "Juliette Verstaen"
date: "8/21/2018"
output: html_document
---

```{r load_packages}

library(tidyverse)
library(readxl)
library(dplyr)
library(ggplot2)


```

```{r load_data}

TEST_coral <- read_excel("TEST_2018_bisc_coral_health_data.xlsx")
TEST_fish <- read_excel("TEST_RVC_Data_2018 2.xlsx")


```

##2018 Hogfish Size Distribution 
**last fish data update 08_21_2018**
```{r}


hogfish_test <- TEST_fish %>%
  filter(fish_com == "hogfish") %>%
  select(fish_com,f_1, f_2, f_3, f_4, f_5, f_6, f_7, f_8, f_9) 

hogfish_test[is.na(hogfish_test)] <- 0

hogfish_one <- hogfish_test%>%
  select (f_1) %>%
  filter(f_1 >0)
colnames(hogfish_one) <- c("total")

hogfish_two <- hogfish_test%>%
  select (f_2) %>%
  filter(f_2 >0)
colnames(hogfish_two) <- c("total")

hogfish_three <- hogfish_test%>%
  select (f_3) %>%
  filter(f_3 >0)
colnames(hogfish_three) <- c("total")

hogfish_four <- hogfish_test%>%
  select (f_4) %>%
  filter(f_4 >0)
colnames(hogfish_four) <- c("total")

hogfish_five <- hogfish_test%>%
  select (f_5) %>%
  filter(f_5 >0)
colnames(hogfish_five) <- c("total")

f_1 <- hogfish_one$total
f_2 <- hogfish_two$total
f_3 <- hogfish_three$total
f_4 <- hogfish_four$total
f_5 <- hogfish_five$total

hf_total <- c(f_1, f_2, f_3, f_4, f_5 )
hf_total_vector <- as.numeric(hf_total_vector)

hist(hf_total_vector)

ggplot() +
  aes(hf_total_vector) +
  geom_histogram(binwidth = 1, colour = "navy", fill = "white")+
  xlab("Hogfish Size (cm)")+
  ylab("Count")+
  ggtitle("Hogfish Size Distribution 2018")+
  geom_vline(xintercept = 40)+
  theme_bw()


```

##Coral Data Wrangling and Exploration

```{r coral_fun}

coral_bleaching <- TEST_coral %>%
  select("field_number", "quadrat", "coral_species", "percent_live", "percent_bleached") %>%
  filter (coral_species != "NA")

coral_siderastrea <- TEST_coral %>%
  select("field_number", "quadrat", "coral_species", "percent_live", "percent_bleached") %>%
  filter (coral_species != "NA") %>%
  filter(coral_species == "siderastrea_radians" | coral_species == "siderastrea_siderea")

sidsid <- TEST_coral %>%
  select("field_number", "quadrat", "coral_species", "percent_live", "percent_bleached") %>%
  filter (coral_species != "NA") %>%
  filter(coral_species == "siderastrea_siderea")

sid_sid <- sidsid$percent_alive
sid_sid <- as.numeric(sid_sid)


sidrad <- TEST_coral %>%
  select("field_number", "quadrat", "coral_species", "percent_live", "percent_bleached") %>%
  filter (coral_species != "NA") %>%
  filter(coral_species == "siderastrea_radians")

sid_rad <- sidrad$percent_alive
sid_rad <- as.numeric(sid_rad)

graph <- 
  ggplot(data = coral_bleaching, aes(x =coral_species, y = coral_bleaching))+
  geom_bar

graph
  

```




















